2024-03-14 22:24:17,680 Minimum price: 10, Maximum price: 350
2024-03-14 22:24:17,687 Preparing sklearn pipeline
2024-03-14 22:24:17,687 Fitting
joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/swatts/miniconda3/envs/mlflow-725491cca606b0888210cf8d014a9e3bb3a1c516/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 273, in _wrap_func_call
    return func()
  File "/home/swatts/miniconda3/envs/mlflow-725491cca606b0888210cf8d014a9e3bb3a1c516/lib/python3.9/site-packages/joblib/parallel.py", line 589, in __call__
    return [func(*args, **kwargs)
  File "/home/swatts/miniconda3/envs/mlflow-725491cca606b0888210cf8d014a9e3bb3a1c516/lib/python3.9/site-packages/joblib/parallel.py", line 589, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/swatts/miniconda3/envs/mlflow-725491cca606b0888210cf8d014a9e3bb3a1c516/lib/python3.9/site-packages/sklearn/utils/fixes.py", line 222, in __call__
    return self.function(*args, **kwargs)
  File "/home/swatts/miniconda3/envs/mlflow-725491cca606b0888210cf8d014a9e3bb3a1c516/lib/python3.9/site-packages/sklearn/ensemble/_forest.py", line 169, in _parallel_build_trees
    tree.fit(X, y, sample_weight=curr_sample_weight, check_input=False)
  File "/home/swatts/miniconda3/envs/mlflow-725491cca606b0888210cf8d014a9e3bb3a1c516/lib/python3.9/site-packages/sklearn/tree/_classes.py", line 898, in fit
    super().fit(
  File "/home/swatts/miniconda3/envs/mlflow-725491cca606b0888210cf8d014a9e3bb3a1c516/lib/python3.9/site-packages/sklearn/tree/_classes.py", line 347, in fit
    criterion = CRITERIA_CLF[self.criterion](self.n_outputs_,
KeyError: 'mae'
"""
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/swatts/Project-Build-an-ML-Pipeline-Starter/src/train_random_forest/run.py", line 297, in <module>
    go(args)
  File "/home/swatts/Project-Build-an-ML-Pipeline-Starter/src/train_random_forest/run.py", line 77, in go
    sk_pipe.fit(X_train, y_train)
  File "/home/swatts/miniconda3/envs/mlflow-725491cca606b0888210cf8d014a9e3bb3a1c516/lib/python3.9/site-packages/sklearn/pipeline.py", line 346, in fit
    self._final_estimator.fit(Xt, y, **fit_params_last_step)
  File "/home/swatts/miniconda3/envs/mlflow-725491cca606b0888210cf8d014a9e3bb3a1c516/lib/python3.9/site-packages/sklearn/ensemble/_forest.py", line 387, in fit
    trees = Parallel(n_jobs=self.n_jobs, verbose=self.verbose,
  File "/home/swatts/miniconda3/envs/mlflow-725491cca606b0888210cf8d014a9e3bb3a1c516/lib/python3.9/site-packages/joblib/parallel.py", line 1952, in __call__
    return output if self.return_generator else list(output)
  File "/home/swatts/miniconda3/envs/mlflow-725491cca606b0888210cf8d014a9e3bb3a1c516/lib/python3.9/site-packages/joblib/parallel.py", line 1595, in _get_outputs
    yield from self._retrieve()
  File "/home/swatts/miniconda3/envs/mlflow-725491cca606b0888210cf8d014a9e3bb3a1c516/lib/python3.9/site-packages/joblib/parallel.py", line 1699, in _retrieve
    self._raise_error_fast()
  File "/home/swatts/miniconda3/envs/mlflow-725491cca606b0888210cf8d014a9e3bb3a1c516/lib/python3.9/site-packages/joblib/parallel.py", line 1734, in _raise_error_fast
    error_job.get_result(self.timeout)
  File "/home/swatts/miniconda3/envs/mlflow-725491cca606b0888210cf8d014a9e3bb3a1c516/lib/python3.9/site-packages/joblib/parallel.py", line 736, in get_result
    return self._return_or_raise()
  File "/home/swatts/miniconda3/envs/mlflow-725491cca606b0888210cf8d014a9e3bb3a1c516/lib/python3.9/site-packages/joblib/parallel.py", line 754, in _return_or_raise
    raise self._result
KeyError: 'mae'